import mongoose from "mongoose";
import { softDeletePlugin } from "@/lib/softDeletePlugin";

const productSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true,
        trim: true,
    },
    slug: {
        type: String,
        required: true,
        unique: true,
        lowercase: true,
        trim: true
    },
    // Stable public identifier — slug can be renamed at will, publicId
    // stays constant for the life of the product. URL shape on the
    // storefront is `/product/<slug>-<publicId>`; lookups match the
    // publicId and 301 to the canonical slug if it's drifted.
    // Generated by lib/publicId.js. Indexed unique. Sparse so the
    // pre-migration documents that lack the field don't conflict.
    publicId: {
        type: String,
        trim: true,
        unique: true,
        sparse: true,
        index: true,
    },
    // Parent style/SKU code shared across variants (admin-defined).
    // Distinct from ProductVariant.sku which is per-variant unique.
    sku: {
        type: String,
        trim: true,
    },
    // Primary category (legacy single ref kept for backward compat).
    // Additional categories can be assigned via `categories[]`.
    category: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Category',
        required: true
    },
    categories: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Category',
    }],
    brand: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Brand',
    },
    // Default-variant price mirror. Custom variants override these
    // per-variant; default variant is auto-kept in sync.
    mrp: {
        type: Number,
        required: true,
    },
    sellingPrice: {
        type: Number,
        required: true,
    },
    discountPercentage: {
        type: Number,
        required: true,
    },
    media: [
        {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Media',
            required: true
        }
    ],
    description: {
        type: String,
        required: true
    },
    // Trimmed marketing blurb shown on listing cards and at the top of
    // the detail page. Distinct from the long `description`.
    shortDescription: {
        type: String,
        trim: true,
    },
    // Publishing workflow. Storefront filters by `status === 'published'`.
    // 'draft' lets admins prepare a product before exposing it; 'archived'
    // hides without deleting (preserves historical references).
    status: {
        type: String,
        enum: ['draft', 'published', 'archived'],
        default: 'published',
        index: true,
    },
    publishAt: {
        type: Date,
    },
    visibility: {
        type: String,
        enum: ['public', 'unlisted'],
        default: 'public',
    },
    // Free-text searchable tags.
    tags: [{
        type: String,
        trim: true,
        lowercase: true,
    }],
    // Per-product variant options (Shopify model). Each option has a
    // name (e.g. "Color") and the list of allowed values for variants
    // of this product. Up to 3 options per product. Variants pick one
    // value per option via `ProductVariant.optionValues[]`.
    //
    //   options: [
    //     { name: 'Color', values: ['Red', 'Blue'], position: 1 },
    //     { name: 'Size',  values: ['S', 'M', 'L'], position: 2 },
    //   ]
    //
    // Empty options = single-SKU product. The admin UI hides the
    // variants table entirely in that case and shows inline price /
    // stock controls instead.
    options: [{
        name: { type: String, required: true, trim: true },
        values: [{ type: String, trim: true }],
        position: { type: Number, default: 0 },
        _id: false,
    }],
    // Static product info — Material, Country, Care instructions, etc.
    // Renders as a Specifications table on the storefront. Distinct
    // from `options` (which drive variants).
    specifications: [{
        name: { type: String, required: true, trim: true },
        value: { type: String, required: true, trim: true },
        _id: false,
    }],
    // Tax / fulfilment hints — used by Module 3 (Orders) when we
    // compute tax and shipping. Optional today.
    taxClass: {
        type: String,
        trim: true,
    },
    shippingClass: {
        type: String,
        trim: true,
    },
    hsnCode: {
        type: String,
        trim: true,
    },
    weight: {
        type: Number,
        default: 0,
    },
    dimensions: {
        length: { type: Number, default: 0 },
        width: { type: Number, default: 0 },
        height: { type: Number, default: 0 },
        _id: false,
    },
    // Storefront listing-card display fields. All optional — empty values
    // gracefully collapse on the card (the field just doesn't render).
    // Keeps card display copy separate from structural fields like
    // `tags` (search-only) and `category` (relational), so admins can
    // tune the on-page presentation without touching either.
    //
    //   badge          — small ribbon ("BEST SELLER", "NEW", etc.)
    //   subtitle       — short descriptor line under the badge image
    //   audienceLabel  — small tag under the name ("For Him", "Unisex")
    //   sizeLabel      — size pill in the corner ("50ml", "1 lb")
    //   highlights[]   — note-style chips below the name
    //   bundleOffer    — promotional line under the price
    card: {
        badge:         { type: String, trim: true, default: '' },
        subtitle:      { type: String, trim: true, default: '' },
        audienceLabel: { type: String, trim: true, default: '' },
        sizeLabel:     { type: String, trim: true, default: '' },
        highlights:    [{ type: String, trim: true }],
        bundleOffer:   { type: String, trim: true, default: '' },
        _id: false,
    },
    // Per-product SEO overrides. Falls back to product name/description
    // when blank. ogImage is a Media reference so the editor can pick
    // from the library.
    seo: {
        title: { type: String, trim: true },
        description: { type: String, trim: true },
        canonical: { type: String, trim: true },
        ogImage: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Media',
        },
        _id: false,
    },
    // Denormalized rollups maintained by Reviews / Orders modules
    // so listing queries don't have to join.
    ratingAvg: { type: Number, default: 0 },
    ratingCount: { type: Number, default: 0 },
    salesCount: { type: Number, default: 0 },
    // Cross-sells and related products for the detail page.
    relatedProducts: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Product',
    }],
    crossSell: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Product',
    }],
    upSell: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Product',
    }],
    deletedAt: {
        type: Date,
        default: null,
        index: true
    },

}, { timestamps: true })


productSchema.index({ category: 1 })
productSchema.index({ brand: 1 })
productSchema.index({ status: 1, deletedAt: 1 })
productSchema.plugin(softDeletePlugin)

/**
 * HMR safety: Next.js dev re-evaluates this file on hot reloads, but
 * mongoose.models persists across reloads. If we don't drop the cached
 * model, Mongoose keeps using the *previous* schema and silently strips
 * any newly-added fields from saves — same hazard we addressed on the
 * Settings model. Production builds load this file once at cold start,
 * so the delete is dev-only.
 */
if (process.env.NODE_ENV !== 'production' && mongoose.models.Product) {
    delete mongoose.models.Product
}

const ProductModel = mongoose.models.Product || mongoose.model('Product', productSchema, 'products')
export default ProductModel
